# Generated by Django 5.2.3 on 2025-06-18 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actress_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=50, unique=True)),
                ('product_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=512)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('review_average', models.FloatField(default=0.0)),
                ('url', models.URLField()),
                ('affiliate_url', models.URLField()),
                ('image_url_small', models.URLField()),
                ('image_url_large', models.URLField()),
                ('sample_image_small', models.URLField(blank=True, null=True)),
                ('sample_image_large', models.URLField(blank=True, null=True)),
                ('sample_movie_476', models.URLField(blank=True, null=True)),
                ('sample_movie_560', models.URLField(blank=True, null=True)),
                ('sample_movie_644', models.URLField(blank=True, null=True)),
                ('sample_movie_720', models.URLField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
                ('delivery_type', models.CharField(max_length=50)),
                ('delivery_price', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('is_pc', models.BooleanField(default=True)),
                ('is_smartphone', models.BooleanField(default=True)),
                ('jancode', models.CharField(blank=True, max_length=13, null=True)),
                ('maker_product', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actresses', models.ManyToManyField(blank=True, to='dmm_items.actress')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmm_items.author')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmm_items.director')),
                ('genre', models.ManyToManyField(blank=True, to='dmm_items.genre')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmm_items.label')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmm_items.maker')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmm_items.series')),
            ],
        ),
    ]
