# Generated by Django 5.2.3 on 2025-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
