# Generated by Django 5.2.3 on 2025-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0002_alter_product_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
