# Generated by Django 5.2.3 on 2025-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0005_product_category_name_product_floor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
