# Generated by Django 5.2.3 on 2025-06-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0006_alter_series_name_alter_series_series_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='maker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
