# Generated by Django 5.2.3 on 2025-06-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0007_alter_maker_maker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='actress_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
