# Generated by Django 5.2.3 on 2025-06-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0008_alter_actress_actress_id_alter_author_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
