# Generated by Django 5.2.3 on 2025-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0011_remove_product_genre_product_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genres',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='actresses',
        ),
        migrations.AddField(
            model_name='product',
            name='actresses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
