# Generated by Django 5.2.3 on 2025-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0012_remove_product_genres_product_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, to='dmm_items.genre'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='actresses',
        ),
        migrations.AddField(
            model_name='product',
            name='actresses',
            field=models.ManyToManyField(blank=True, to='dmm_items.actress'),
        ),
    ]
