# Generated by Django 5.2.3 on 2025-07-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0015_product_campaign_date_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campaign_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
