# Generated by Django 5.2.3 on 2025-07-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0016_product_campaign_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
