# Generated by Django 5.2.3 on 2025-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0017_product_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sample_movie_476',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample_movie_560',
        ),
    ]
