# Generated by Django 5.2.3 on 2025-07-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0017_product_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='floor_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='floor_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
