# Generated by Django 5.2.3 on 2025-07-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0022_alter_product_campaign_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actresses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
