# Generated by Django 5.2.3 on 2025-07-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0023_alter_product_actresses_alter_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
