# Generated by Django 5.2.3 on 2025-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0024_alter_product_actresses_alter_product_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sample_image_large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample_image_small',
        ),
    ]
