# Generated by Django 5.2.3 on 2025-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0025_remove_product_sample_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
