# Generated by Django 5.2.3 on 2025-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm_items', '0026_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.TextField(blank=True, null=True),
        ),
    ]
