services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dmm_db
      - POSTGRES_USER=yutaka
      - POSTGRES_PASSWORD=Honebuto095@pos
    restart: always

  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 --timeout 600 --workers 3 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DATABASE_URL=postgres://yutaka:Honebuto095%40pos@db:5432/dmm_db
      - DEBUG=False
    env_file: ".env"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8880:80"
    volumes:
      - ./config/django_backend:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume: